name: 'PR $(System.PullRequest.PullRequestId)'

trigger:
    branches:
        exclude:
            - '*'
pr:
    autoCancel: false
    branches:
        include:
            - main
            - master
    paths:
        exclude:
            - './**/*.md'
            - './xUnitHelpers/.Examples/*'


variables:
    - template: azure-pipelines.vars.yml

jobs:
    - template: azure-pipelines.common.yml
      parameters:
          message: 'PR $(System.PullRequest.PullRequestNumber) $(System.PullRequest.SourceBranch)'
